### ISSUE TITLE
AppVeyor shows unknown status

### ISSUE THREAD

**Issue by jgfoster** [Arduino-CI/Blink#12]
It appears that the test runs successfully but isn't getting marked as passed.

**Comment by hlovdal** [comment]
There is nothing in the actual `.appveyor.yml` file that is causing this. I have tested by removing everything arduino specific and using nothing but `echo` commands without any difference.

I tested by setting up AppVeyor on my fork and adding a couple of [new badge links](https://github.com/hlovdal/Blink/tree/issue_12_troubleshooting), and they all behave like expected.

So there is something with the https://ci.appveyor.com/api/projects/status/rjm4txik4wpmthh0?svg=true link that is not working. It shows unknown regardless of success or failure of the build.

@ianfixes Could you go to https://ci.appveyor.com/project/ianfixes/blink/settings/badges and copy the url/markdown from there and paste into README.md to verify that the link is correct? I strongly suspect this must be the issue. If I deliberately invalidate my working badge url it also shows status unknown.

**Comment by ianfixes** [comment]
hmmm...
```markdown
[![Build status](https://ci.appveyor.com/api/projects/status/3q9fp44hmpl8yjso?svg=true)](https://ci.appveyor.com/project/ianfixes/blink)
```

it points to the ianfixes fork.  it may be that we haven't actually configured appveyor to hit the organization's repo

**Comment by ianfixes** [comment]
I guess the appveyor URL is a red herring, the project seems to be correctly testing the `ArduinoCI/Blink` repo.

**Comment by ianfixes** [comment]
I'm not sure what aspect of this caused the break to the badge, but I apologize for not fixing it sooner and for all the time you both spent looking into what was effectively a quick fix by copy-pasting from their site.

**Comment by hlovdal** [comment]
Excellent that the issue is fixed. This issue can now be closed.
