### ISSUE TITLE
AppVeyor Integration

### ISSUE THREAD

**Issue by jgfoster** [Arduino-CI/Blink#2]
For this project to be a good demo, we should set up CI testing on various testing platforms. I created an account at AppVeyor and tried to install AppVeyor in this project (`Arduino-CI / Blink`) but got an error when attempting to authorize access to GitHub. I suspect that this is because I don't have proper permissions. 

It appears that the external CI platforms require setup by an owner of the organization, not just a manager of the project.

**Comment by ianfixes** [comment]
This has been enabled

**Comment by jgfoster** [comment]
The `README.md` still references `prestoncarman/blink`. I can change that but I don't know your project status identifier. Could you provide that or edit `README.md`?

**Comment by ianfixes** [comment]
Good catch, opened https://github.com/Arduino-CI/Blink/pull/8
