### ISSUE TITLE
Use Arduino-CI official GitHub Action

### ISSUE THREAD

**Issue by prestoncarman** [Arduino-CI/Blink#9]
Switch out the Ubuntu version for GitHub Actions to use the official released action.

**Comment by jgfoster** [comment]
https://github.com/jgfoster/Blink/runs/1475688308?check_suite_focus=true

**Comment by ianfixes** [comment]
`Arduino-CI/action@v0.1.1` should work

**Comment by jgfoster** [comment]
Fixed with #11.
